### ISSUE TITLE
求解~感谢

### ISSUE THREAD

**Issue by daisy-cyt** [phodal/weapp-webdemo#2]
看了您的一些列关于微信小程序的文章，对它的底层机制有初步了解了，十分感谢，但是有些问题不是很清楚。
微信小程序到底是运行在webview还是natvie上的呢？ 看到wxml中的标签都被转换成了wx- 的标签，感觉应该是偏native的，可是wxss的写法基本就是css，如果是native，css是怎么渲染的呢？

**Comment by phodal** [comment]
@daisy-cyt 这部分的内容是 x5 浏览器来渲染的~~，和微信小程序没啥关系。你可以了解一个 WebKit 的渲染机制。
