### ISSUE TITLE
运行下载的代码，显示空白一片

### ISSUE THREAD

**Issue by taiji1985** [phodal/weapp-webdemo#4]
您好，下载了您的代码，运行后一片空白。 console也没有报错。不知道是什么原因？O(∩_∩)O~

您给出示例网址是没问题的。

**Comment by phodal** [comment]
@taiji1985 我猜是因为资源加载的问题

**Comment by taiji1985** [comment]
@phodal  看了您的其他几篇文章，弄明白了这个问题。
$gwx('test.wxml') 这个函数的参数要正确，不然会返回一个undefined。

$gwx('test.wxml')('test') 这样会生成一个json。 但如果第一个是undefined，就不会生成。

我看了您的demo，和git上的版本的另一个差别是，这里面有Page等函数的定义。而new-split这个Page.js里似乎没有？？？

**Comment by tongxin3267** [comment]
@phodal 我的也是空白的。请问怎么解决

**Comment by leehongsen** [comment]
同求，是空白的

**Comment by phodal** [comment]
想起来了，切换到 gh-pages 分支就好了
