### ISSUE TITLE
有关信小程序在pc浏览器上的运行环境的问题

### ISSUE THREAD

**Issue by leehongsen** [phodal/weapp-webdemo#5]
你好，想跟你请教个问题：那个微信小程序在pc浏览器上的运行环境，如果运行的小程序页面很多，要一次全部都执行吗？有一部分我没有理解,他的目录结构是怎样的？能详细解析一下吗？谢谢。。

**Comment by phodal** [comment]
这只是一个 demo 哦，剩下的要自己玩~
